### ISSUE TITLE
Hi, I am the original author of the"VGTab"

### ISSUE THREAD

**Issue by lihaoyun6** [corpnewt/VGTabMerge#1]
I am very happy to see the contribution of your work to hackintosh.
And maybe you can put the original link of "VGTab" in the contribution list.
Best wishes from a Chinese developer :)

**Comment by lihaoyun6** [comment]
link of "VGTab":
http://bbs.pcbeta.com/viewthread-1786481-1-1.html

**Comment by corpnewt** [comment]
I updated the readme with the link to the app and your github.

Thanks for reaching out,

-CorpNewt
